name: CI

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Connect Nuget source
      run: dotnet nuget add source --username stringit-app --password ${{ secrets.READ_PACKAGE_TOKEN }} --store-password-in-clear-text --name github https://nuget.pkg.github.com/stringit/index.json
    - name: Restore dependencies
      run: dotnet restore Source/Mapack.sln
    - name: Build
      run: dotnet build Source/Mapack.sln --no-restore -c Release
    - name: Test
      run: dotnet test Source/Mapack.sln -c Release --no-build --verbosity normal
    - name: Pack
      if: github.event_name != 'pull_request'
      run: dotnet pack Source/Mapack.sln -c Release --no-build -o package
    - name: Push generated package to GitHub registry
      if: github.event_name != 'pull_request'
      run: dotnet nuget push ./package/*.nupkg --source https://nuget.pkg.github.com/stringit/index.json --api-key ${{ github.token }} --skip-duplicate
